### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by polyrainbow** [goolord/tundra#3]
I saw your [PR on rodio](https://github.com/RustAudio/rodio/pull/430) and would like to use that code in [my own project](https://github.com/SebastianZimmer/miconau) as long as it is not merged yet. However, this repository does not contain any license information. Would it be possible to add a FOSS license?

**Comment by goolord** [comment]
https://github.com/goolord/tundra/commit/ce2043164bd1c9a74936dfc0a0ecb1415aa7e678

added the MIT license, go ham o7

**Comment by polyrainbow** [comment]
Very cool. Thanks a lot!
